springdoc:
  version: 2.0
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    url: jdbc:postgresql://localhost/alexandria
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  flyway:
    validateOnMigrate: false
  messages:
    basename: messages

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} [%-3level] [%-10thread] [%C{0}@%L]: %msg%n'

server:
  error:
    include-message: always
